### PR TITLE
Improve Search with Highlighting and Debounced Input

### PR DESCRIPTION
**Pull request by PATILYASHH**
### Description

- **Highlight Matching Text**: Highlight matching text in search results.
- **Debounced Search**: Improved search performance with debouncing.

### Changes

- Updated `script.js` to highlight matching text.
- Added debouncing to the search input for better performance.

### Testing

- Verify matching text is highlighted.
- Confirm improved performance with debounced search input.
### img -

ss11

### CODE REVIEW

**Comment by PATILYASHH** [comment]
if u want then i can show u prototype

**Review by narainkarthikv — CHANGES_REQUESTED** [review]
Hi @PATILYASHH, as I could see there was an issue through the image you shared during the PR. Review the changes and modify the code.

**Comment by PATILYASHH** [comment]
> Hi @PATILYASHH, as I could see there was an issue through the image you shared during the PR. Review the changes and modify the code.
can you tell me what is issue ?

**Comment by PATILYASHH** [comment]
https://5500-patilyashh-nmoji-f6n8a2lq40h.ws-us115.gitpod.io/    take a look and you think there is any issue then tell me i will try my best to fix it

**Comment by narainkarthikv** [comment]
I can't access the link you provided, @PATILYASHH.

Can you help me with another issue if you're willing? It involves HTML & CSS. I'll look further into the code and get back to you about the issue you faced in the meantime.

You can check out the details here: [github-issue #3](https://github.com/narainkarthikv/Nmoji/issues/3).

image

**Pull request closed without merging**
